import type { AppDefinition, AppCategory } from "@/types";

export const APP_CATEGORIES: AppCategory[] = [
  "All",
  "Productivity & Finance",
  "Social",
  "Utilities",
  "Creativity",
  "Entertainment",
  "Information & Reading",
  "Other",
];

export const APP_REGISTRY: Record<string, AppDefinition> = {
  terminal: {
    id: "terminal",
    name: "kitty",
    category: "Utilities",
    icon: "Kitty",
    gradient: "from-zinc-800 to-black",
    defaultSize: { width: 680, height: 420 },
    minSize: { width: 400, height: 250 },
  },
  "file-manager": {
    id: "file-manager",
    name: "Files",
    category: "Utilities",
    icon: "Folder",
    gradient: "from-blue-400 to-blue-600",
    defaultSize: { width: 720, height: 480 },
    minSize: { width: 400, height: 300 },
  },
  "text-editor": {
    id: "text-editor",
    name: "Editor",
    category: "Productivity & Finance",
    icon: "FileText",
    gradient: "from-amber-400 to-amber-600",
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 360, height: 280 },
  },
  "system-monitor": {
    id: "system-monitor",
    name: "System Monitor",
    category: "Information & Reading",
    icon: "Activity",
    gradient: "from-emerald-400 to-teal-600",
    defaultSize: { width: 600, height: 400 },
    minSize: { width: 400, height: 300 },
  },
  firefox: {
    id: "firefox",
    name: "Firefox",
    category: "Social",
    icon: "Globe",
    gradient: "from-orange-500 via-rose-500 to-purple-600",
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 400, height: 300 },
  },
  music: {
    id: "music",
    name: "Music",
    category: "Entertainment",
    icon: "AudioLines",
    gradient: "from-rose-400 to-pink-600",
    defaultSize: { width: 500, height: 400 },
    minSize: { width: 350, height: 300 },
  },
  video: {
    id: "video",
    name: "mpv",
    category: "Entertainment",
    icon: "Clapperboard",
    gradient: "from-purple-500 to-indigo-700",
    defaultSize: { width: 640, height: 360 },
    minSize: { width: 400, height: 225 },
  },
  portfolio: {
    id: "portfolio",
    name: "Portfolio",
    category: "Productivity & Finance",
    icon: "User",
    gradient: "from-amber-500 to-yellow-600",
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 400, height: 300 },
  },
  resume: {
    id: "resume",
    name: "Resume",
    category: "Productivity & Finance",
    icon: "FileText",
    gradient: "from-sky-400 to-blue-600",
    defaultSize: { width: 760, height: 600 },
    minSize: { width: 400, height: 300 },
  },
  calendar: {
    id: "calendar",
    name: "Calendar",
    category: "Information & Reading",
    icon: "Calendar",
    gradient: "from-rose-500 to-red-600",
    defaultSize: { width: 680, height: 480 },
    minSize: { width: 420, height: 320 },
  },
  settings: {
    id: "settings",
    name: "Settings",
    category: "Utilities",
    icon: "Settings",
    gradient: "from-slate-500 to-zinc-700",
    defaultSize: { width: 740, height: 500 },
    minSize: { width: 480, height: 350 },
  },
  "ai-studio": {
    id: "ai-studio",
    name: "AI Studio",
    category: "Creativity",
    icon: "Brain",
    gradient: "from-violet-500 to-purple-800",
    defaultSize: { width: 780, height: 560 },
    minSize: { width: 440, height: 340 },
  },
};
